### ISSUE TITLE
Use condition name for 'Condition' node in pipeline run child nodes

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/vscode-tekton#277]
Now if task has condition we add item in the tree with task name not with condition name:
<img width="1440" alt="Screenshot 2020-05-07 at 17 43 38" src="https://user-images.githubusercontent.com/929743/81308690-bed8fe80-908a-11ea-9651-9fefd41c01c0.png">

We need to use condition name for that tree item.

**Comment by evidolob** [comment]
@siamaksade We are showing condition run as taskrun nodes, but `intellij-tekton` add condition run as child to taskrun, see https://github.com/redhat-developer/intellij-tekton/pull/94
Should we alight with them?

**Comment by lstocchi** [comment]
I just want to add that we display conditions in two different ways based on the position in the tree. The one Yevhen described, as children of a taskrun node under a pipelinerun node and as normal taskrun nodes under the taskruns root node. 

We took this decision because we thought it would be clearer from a user perspective to understand which condition failed and what was the task it was related to when starting a pipeline, but we show them as normal taskrun nodes under taskrun root node because they are treated as taskruns in tekton.

BTW we are open to suggestion as well. If you find a better solution we are always ready to steal it from vscode ;) And also, if you need any other info, feel free to ask :)

**Comment by gorkem** [comment]
I was going to ask for this, @evidolob looks like you have beaten me to it. I think the way intellij-tekton shows conditions on a pipelinerun is more helpful, +1 to converge on that.
