### ISSUE TITLE
Configure the extension to use my local dev tkn?

### ISSUE THREAD

**Issue by bobcatfish** [redhat-developer/vscode-tekton#73]
Thanks for making this!! :D :heart: 

I tried to install it today but ran into trouble because though I _do_ have `tkn` installed (built from source), the extension thought it was not installed (p.s. I really like the design, how the extension uses the cli, very cool!) b/c the version was "dev" and not v0.3.0

What I did was:
1. Installed the latest build  (Nov 3?) (instructions from https://github.com/redhat-developer/vscode-tekton#warning-nightly-builds-are-by-definition-unstable-install-at-you-own-risk)
2. Tried to run `> Tekton: About`
3. Got the error: "Cannot find A CLI for interacting with Tekton v0.3.0."
4. Hit the "help" button
5. A terminal popped up, when I tried to run `tkn` it wasn't found, and also I didnt recognize the `$PATH`, it doesn't seem to be the one I usually see when I run `/bin/bash` or similar

I finally worked around this by installing version 0.3.0 of the CLI instead of the dev version - is it possible for there to be a mode that allows me to use the dev CLI and/or not care what version of the CLI is installed?

**Comment by dgolovin** [comment]
@bobcatfish Thank you for reaching out! 

The extension is configured to use only `tkn` with version that matches range defined in https://github.com/redhat-developer/vscode-tekton/blob/f83fdaa283344c4a38e40cd91f41fecae0c60ba7/src/tools.json#L8 which is semver version range. 

I agree there should be a way to tell extension 'I want to use this specific `tkn` binary', because that would be very convenient for testing with new releases and development builds. 
We can add third option 'Point to `tkn' location` to `Cannot find A CLI for interacting with Tekton v0.3.0.` message. It would open file selection dialog and let you to select `tkn` to use.  Would that work?

**Comment by dgolovin** [comment]
@bobcatfish there is another undocumented workaround. When you get message 'Cannot find A CLI for interacting with Tekton v0.3.0.` select 'Download and install' option. After download is finished copy your dev version of `tkn` over `~/.vs-tekton/tkn`. For the current session it will just use your dev version without checking version. When after restart you see "Cannot find A CLI for interacting with Tekton v0.3.0." message again just select `Cancel` option and extension will use `~/.vs-tekton/tkn` anyway.

**Comment by siamaksade** [comment]
Fixed by https://github.com/redhat-developer/vscode-tekton/issues/116
